/** Normaliseer zichtbare tekst: geen em dash, en dash of middot als scheiding. */
export function sanitizeVisibleCopy(text: string): string {
  return text
    .replace(/\s*—\s*/g, ', ')
    .replace(/(\d{1,2}:\d{2})\s*[–—]\s*(\d{1,2}:\d{2})/g, '$1 tot $2')
    .replace(/\b(Dinsdag)\s*[–—]\s*(zondag)\b/gi, '$1 t/m $2')
    .replace(/\b(Di)\s*[–—]\s*(Zo|zo)\b/g, (_, di, zo) => `${di} t/m ${zo.toLowerCase()}`)
    .replace(/\s*·\s*/g, ', ')
    .replace(/\s*[–—]\s*/g, ' tot ')
    .replace(/\beigenmanschap\b/gi, 'nieuwe eigenaren')
    .replace(/\bonder nieuw eigenmanschap\b/gi, 'door nieuwe eigenaren')
    .replace(/\bonder nieuwe eigenaren heropend\b/gi, 'door nieuwe eigenaren heropend')
    .replace(/\bhoutgestookte pizza-oven\b/gi, 'pizza uit de houtoven')
    .replace(/\bhoutgestookte pizza oven\b/gi, 'pizza uit de houtoven')
    .replace(/\bhoutoven-pizza\b/gi, 'pizza uit de houtoven')
    .replace(/\bhoutovenpizza\b/gi, 'pizza uit de houtoven')
    .replace(/\bWaterfront terras\b/gi, 'Terras aan het water')
    .replace(/\bWaterfront\b/gi, 'Aan het water')
    .replace(/\bSfeer & ambiance\b/gi, 'Sfeer & beleving')
    .replace(/\bambiance\b/gi, 'sfeer')
    .replace(/\bKnus binnen & knap buiten\b/gi, 'Gezellig binnen en buiten')
    .replace(/\bKnus & sfeervol\b/gi, 'Warm en sfeervol')
    .replace(/\bknus thuisgevoel\b/gi, 'warm thuisgevoel')
    .replace(/\bKnus aan de bar\b/gi, 'Gezellig aan de bar')
    .replace(/\bKnus & warm\b/gi, 'Warm en sfeervol')
    .replace(/\bcharcuterie\b/gi, 'vleeswaren')
    .replace(/\bOpen vuur\b/gi, 'Houtoven')
    .replace(/\bfeedback\b/gi, 'een reactie')
    .replace(/\bEigenaars\b/g, 'Eigenaren')
    .replace(/,\s*de houtoven en\b/gi, ', pizza uit de houtoven en')
    .replace(/\bmet terras, houtoven en\b/gi, 'met terras, pizza uit de houtoven en')
    .replace(/\bterras, de houtoven en\b/gi, 'terras, pizza uit de houtoven en')
    .replace(/,\s*houtoven en\b/gi, ', pizza uit de houtoven en')
    .replace(/geur van de houtoven\b/gi, 'geur van pizza uit de houtoven')
    .replace(/,\s*,/g, ',')
    .replace(/\.\s*\./g, '.')
    .trim()
}
